AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudTrail API Activity Alarm Template for CloudWatch Logs"
Parameters:
  LogGroupName:
    Type: "String"
    Default: "CloudTrail/DefaultLogGroup"
    Description: "Enter CloudWatch Logs log group name. Default is CloudTrail/DefaultLogGroup"
  Email:
    Type: "String"
    Description: "Email address to notify when an API activity has triggered an alarm"

Resources:
  AlarmNotificationTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        - Endpoint: !Ref "Email"
          Protocol: "email"
  ConsoleLoginsWithoutMFAAlerm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: "CloudTrailConsoleLoginWithoutMFA"
      AlarmDescription: "Alarms when the sign-in to console without MFA device is recorded"
      AlarmActions:
        - !Ref "AlarmNotificationTopic"
      MetricName: "ConsoleLoginsWithoutMFA"
      Namespace: "CloudTrailMetrics"
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      EvaluationPeriods: "1"
      Period: "300"
      Statistic: "Sum"
      Threshold: "1"
      TreatMissingData: "notBreaching"
  ConsoleLoginsWithoutMFAMetricFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      LogGroupName: !Ref "LogGroupName"
      FilterPattern: '{ $.eventName = "ConsoleLogin" && $.additionalEventData.MFAUsed = "No" }'
      MetricTransformations:
        - MetricNamespace: "CloudTrailMetrics"
          MetricName: "ConsoleLoginsWithoutMFA"
          MetricValue: "1"
  RootAccountUsagesAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: "CloudTrailRootAccountUsages"
      AlarmDescription: "Alarms when the usage of the root user is recorded"
      AlarmActions:
        - !Ref "AlarmNotificationTopic"
      MetricName: "RootAccountUsageCount"
      Namespace: "CloudTrailMetrics"
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      EvaluationPeriods: "1"
      Period: "300"
      Statistic: "Sum"
      Threshold: "1"
      TreatMissingData: "notBreaching"
  RootAccountUsageMetricFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      LogGroupName: !Ref "LogGroupName"
      FilterPattern: '{$.userIdentity.type="Root" && $.userIdentity.invokedBy NOT EXISTS && $.eventType !="AwsServiceEvent"}'
      MetricTransformations:
        - MetricNamespace: "CloudTrailMetrics"
          MetricName: "RootAccountUsageCount"
          MetricValue: "1"
